use std::fmt;

/// A character's position in Lynx source text.
#[derive(Debug, Clone, Copy)]
pub struct Pos(
    /// Line number starting from `1`.
    pub usize,
    /// Column number starting from `1`
    /// (meanwhile the `\n` at the end of line `n` is denoted by `Pos(n+1, 0)`).
    pub usize,
);

impl fmt::Display for Pos {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}:{}", self.0, self.1)
    }
}

/// The position of a span of characters in Lynx source text,
/// delimited by two [`Pos`]s.
#[derive(Debug, Clone, Copy)]
pub struct Span(
    /// Start position.
    pub Pos,
    /// End position (inclusive).
    pub Pos,
);

impl fmt::Display for Span {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{} - {}", self.0, self.1)
    }
}

/// Various kinds of tokens.
#[derive(Debug, Clone)]
pub enum TokenKind {
    /// Identifiers.
    Id(
        /// The name of the identifier.
        String,
    ),

    /// Binary operators.
    BinOp(
        /// The name of the operator.
        String,
    ),

    /// Interger literal.
    IntLit(
        /// The value of the literal.
        i64,
    ),

    /// Floating-point number literal.
    FloatLit(
        /// The value of the literal.
        f64,
    ),

    /// Character literal.
    CharLit(
        /// The value of the literal.
        char,
    ),

    /// String literal.
    StrLit(
        /// The value of the literal.
        String,
    ),

    // Alphabetic keywords
    /// The keyword `ctor`.
    Ctor,
    /// The keyword `import`.
    Import,
    /// The keyword `_`.
    Underscore,

    // Symbolic keywords
    /// The keyword `:`.
    Colon,
    /// The keyword `::`.
    DoubleColon,
    /// The keyword `.`.
    Dot,
    /// The keyword `->`.
    Arrow,
    /// The keyword `=>`.
    FatArrow,
    /// The keyword `=`.
    Bind,
    /// The keyword `@`.
    At,
    /// The keyword `|`.
    Pipe,
    /// The keyword `#`.
    Hash,
    /// The keyword `%`.
    Percent,
    /// The keyword `~`.
    Tilde,
    /// The keyword `%~`.
    PercentTilde,
    /// The keyword `(` (left parenthesis).
    Lp,
    /// The keyword `)` (right parenthesis).
    Rp,
    /// The keyword `[` (left bracket).
    Lb,
    /// The keyword `]` (right bracket).
    Rb,
    /// The keyword `{` (left curly brace).
    Lc,
    /// The keyword `}` (right curly brace).
    Rc,
    /// The keyword `,`.
    Comma,
    /// End of expression (i.e. `;` or blank line),
    /// also considered a keyword.
    ExprEnd,
}

/// A token of Lynx code, generated by [`Lexer`](crate::lexer::Lexer).
#[derive(Debug, Clone)]
pub struct Token(pub TokenKind, pub Span);
